version: '1.0'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: chatapp
    volumes:
      - ./pgdata:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
  app:
    image: chatapp-server
    environment:
      - NODE_ENV=development
    ports:
      - "8081:8081"
    depends_on:
      - db 
    env_file:
      - .env




